#ifndef ELECTIONCORE_GLOBAL_H
#define ELECTIONCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ELECTIONCORE_LIBRARY)
#  define ELECTIONCORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define ELECTIONCORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ELECTIONCORE_GLOBAL_H